name: Update Wakatime Stats

on:
  schedule:
    - cron: "0 0 * * *"      # every day at midnight UTC
  workflow_dispatch:        # allows you to run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol-wakatime/readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "true"
          SHOW_OS: "true"
          SHOW_EDITORS: "true"
          SHOW_PROJECTS: "false"
          SHOW_TIMEZONE: "false"
          SHOW_DAYS: "7"
          SHOW_LANGUAGE: "true"
          SYMBOL_STYLE: "round"
